[package]
name = "pam"
version = "0.1.0"
edition = "2018"

[[bench]]
name = "bench"
harness = false

[dependencies]
num-traits = "0.2.14"
rand = "0.8.3"

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"]}